import Head from "next/head";
import styled from "styled-components";
import tw from "twin.macro";
import Banner from "../components/Banner/Banner";
import Container from "../components/Container/Container";
import Header from "../components/Header/Header";
import NavBar from "../components/NavBar/NavBar";
import Link from "next/link";

const Main = styled.main`
    & > * {
        ${tw`mt-7 block`}
    }
`;

const NewJobLink = styled.div`
    ${tw`px-3 bg-gray-700 pb-5`}

    @media screen and (min-width: 1024px) {
        ${tw`bg-transparent pb-8`}
    }

    .link {
        ${tw`text-white bg-blue-400 rounded-lg p-3 px-5 inline-block font-semibold`}
    }
`;

const Hiring = () => {    
    const description = "Senza's flexible and scalable solutions make it easier for companies of all sizes to find the best talent in no time while saving costs."
    
    return (
        <>
            <Head>
                <title>Senza - For Employers</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <Header>
                <div className="container">
                    <NavBar />
                    <Banner title="We're here to make hiring easier." description={description}/>
                    <NewJobLink>
                        <Link href="/jobs/new" scroll={false}>
                            <a className="link">
                                Post a job now
                            </a>
                        </Link>
                    </NewJobLink>
                </div>
            </Header>
            <Container>
                <Main>
                    TODO: Brag about how we're good for employers
                </Main>
            </Container>
        </>
    )
}

export default Hiring