import tw from 'twin.macro'
import Head from 'next/head'
import styled from 'styled-components'
import JobSummaryList from '../components/JobSummary/JobSummaryList';
import PostJobBanner from '../components/PostJob/PostJobBanner';
import CategoryList from '../components/Category/CategoryList';
import SearchBar from '../components/Search/SearchBar';

const Main = styled.main`
  & > * {
    ${tw`mt-7 block`}
  }
`;

const Header = styled.div`
  display: flex;
  min-height: 15em;
  flex-direction: column;
`;

const TopHeader = styled.div`
  ${tw`p-1 bg-purple-700 rounded-b-lg shadow-lg flex-grow`}
`;

export default function Home() {
  const jobs = [{}, {}, {}, {}, {}, {}, {}];
  const categories = ['Accounting & Finance', 'Programming', 'Secretary', 'Driving', 'Software Development', 'Mining & Farming', 'Shop Keeping', 'Another', 'Different One', 'Ari Kupisa'];

  return (
    <>
      <Head>
        <title>Mobile Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>

      <Header>
        <TopHeader>
          Top Header
        </TopHeader>

        <SearchBar />
      </Header>

      <Main>
        <CategoryList categories={categories} />
        <PostJobBanner />
        <JobSummaryList jobs={jobs}/>
      </Main>
    </>
  )
}
