import tw from 'twin.macro'
import Head from 'next/head'
import styled from 'styled-components'

const Main = styled.main`
    ${tw`bg-gray-50`}
    min-height: 100vh;
    padding: 0 0.5rem;
`;

const P = styled.p`
  ${tw`text-red-500 text-xl font-semibold py-3`}
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <P>
          Hello World
        </P>
      </Main>
    </>
  )
}
