import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styled from "styled-components";
import tw from "twin.macro";
import Container from "../components/Container/Container";
import Header from "../components/Header/Header";
import JobSummaryList from "../components/JobSummary/JobSummaryList";
import NavBar from "../components/NavBar/NavBar";
import MainSearch from "../components/Search/MainSearch";

const Main = styled.main`
    & > * {
        ${tw`mt-7 block`}
    }
`;

const SearchPage = () => {
    const router = useRouter()
    const [jobs, setJobs] = useState();
    const [timer, setTimer] = useState(null);
    const [query, setQuery] = useState(router?.query?.q ?? '')
    const [location, setLocation] = useState(router?.query?.location ?? '')

    useEffect(async () => {
        if (timer) clearTimeout(timer)

        if (query.length > 3) {
            setTimer(setTimeout(async () => {setJobs(await axios.get(`${process.env.NEXT_PUBLIC_CORE_SERVICE_ENDPOINT}/search?q=${query}&location=${location}`).then(r => r.data))}, 1000))
        }

        if (query.length <= 3) {
            setTimer(setTimeout(async () => {setJobs(await axios.get(`${process.env.NEXT_PUBLIC_CORE_SERVICE_ENDPOINT}/jobs/latest`).then(r => r.data))}, 1000))
        }

        router.replace({
            pathname: '/search',
            query: { q: query, location },
        })
    }, [query, location])

    return (
        <>
            <Head>
                <title>Senza - Search Page</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <Header>
                <div className="container">
                    <NavBar />
                </div>
            </Header>
            <Container>
                <Main>
                    <MainSearch query={query} location={location} setQuery={setQuery} setLocation={setLocation} />
                    <JobSummaryList title={`${query && query.length > 3 ? 'Search results' : 'Latest jobs'}`} jobs={jobs} />
                </Main>
            </Container>
        </>
    )
}

export default SearchPage