import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styled from "styled-components";
import tw from "twin.macro";
import Container from "../components/Container/Container";
import Header from "../components/Header/Header";
import JobSummaryList from "../components/JobSummary/JobSummaryList";
import NavBar from "../components/NavBar/NavBar";
import MainSearch from "../components/Search/MainSearch";

const Main = styled.main`
    & > * {
        ${tw`mt-7 block`}
    }
`;

const SearchPage = () => {
    const router = useRouter()
    const [timer, setTimer] = useState(null);
    const [search, setSearch] = useState(false);
    const [query, setQuery] = useState(router?.query?.q ?? '')
    const [location, setLocation] = useState(router?.query?.location ?? '')

    const prevPages = typeof window == 'object' ? JSON.parse(localStorage.getItem(`${window.location.href}_all-pages`)) : null;
    const allJobs = prevPages ? prevPages.filter(el => !!el).reduce((allJobs, el) => allJobs.concat(el?.data), []) : null;
    const lastPage = prevPages ? prevPages[prevPages.length - 1] : null;
    const [jobs, setJobs] = useState(lastPage && allJobs ? {...lastPage, data: allJobs} : undefined);

    useEffect(() => {
        let previousPage = localStorage.getItem('previousPage')

        if (!(previousPage === 'job_details')) {
            setJobs(undefined);
            if (query.length > 3) {
                setTimer(setTimeout(async () => {setJobs(await axios.get(`${process.env.NEXT_PUBLIC_CORE_SERVICE_ENDPOINT}/search?q=${query}&location=${location}`).then(r => r.data))}, 1000))
            }
    
            if (query.length <= 3) {
                setTimer(setTimeout(async () => {setJobs(await axios.get(`${process.env.NEXT_PUBLIC_CORE_SERVICE_ENDPOINT}/jobs/latest`).then(r => r.data))}, 1000))
            }
        }

        return () => {
            localStorage.setItem('previousPage', 'search')
        }
    }, [])

    useEffect(() => {
        if (timer) clearTimeout(timer)

        if (search) {
            if (query.length > 3) {
                setTimer(setTimeout(async () => {setJobs(await axios.get(`${process.env.NEXT_PUBLIC_CORE_SERVICE_ENDPOINT}/search?q=${query}&location=${location}`).then(r => r.data))}, 1000))
            }
    
            if (query.length <= 3) {
                setTimer(setTimeout(async () => {setJobs(await axios.get(`${process.env.NEXT_PUBLIC_CORE_SERVICE_ENDPOINT}/jobs/latest`).then(r => r.data))}, 1000))
            }
        }

        return () => {
            if (timer) clearTimeout(timer)
        }
    }, [query, location])

    const onQueryChange = e => {
        setQuery(e.target.value)
        setSearch(true)
    }

    const onLocationChange = e => {
        setLocation(e.target.value)
        setSearch(true)
    }

    return (
        <>
            <Head>
                <title>Senza - Search Page</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <Header>
                <div className="container">
                    <NavBar />
                </div>
            </Header>
            <Container>
                <Main>
                    <MainSearch query={query} location={location} setQuery={onQueryChange} setLocation={onLocationChange} />
                    <JobSummaryList title={`${query && query.length > 3 ? 'Search results' : 'Latest jobs'}`} jobs={jobs} />
                </Main>
            </Container>
        </>
    )
}

export default SearchPage