import tw from 'twin.macro'
import Head from 'next/head'
import styled from 'styled-components'

const Main = styled.div`
    ${tw`min-h-screen bg-purple-100 flex`}
    flex-direction: column;
`;

const Top = styled.div`
    ${tw`px-2 py-4`}
`;

const Bottom = styled.div`
    ${tw`px-2 py-4 shadow-lg bg-gray-50 rounded-t-xl`}
    flex-grow: 1;
`;

const Single = () => (
    <>
        <Head>
            <title>Mobile - Job Details</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
        </Head>

        <Main>
            <Top>
                Top
            </Top>
            <Bottom>
                Bottom
            </Bottom>
        </Main>
    </>
)

export default Single